@startuml
!NEW_C4_STYLE=1
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

title Context Diagram fot Bank Standart Online products (MVP)

Person_Ext(user, "Пользователь", "")
Person_Ext(client, "Клиент", "")

System_Boundary(bank, "Банк Стандарт") {
    System(site, "Сайт", "")
    System(internet_bank, "Интернет-банк", "")
    Person(operator, "Оператор Колл-центра", "")
}

Rel(user, site, "Выбирает условия по депозиту, заполняет форму обратного звонка", "")
Rel(client, internet_bank, "Выбирает условия по депозиту, подтверждает заявку", "")

Rel(operator, user, "Отрабатывает заявку с формы, подтверждает ставку", "")
Rel(internet_bank, client, "СМС")

@enduml